export const Config = {
  STRAPI_API_TOKEN : process.env.EXPO_PUBLIC_STRAPI_API_TOKEN,
  STRAPI_URL_BASE : process.env.EXPO_PUBLIC_STRAPI_URL_BASE,
  DEFAULT_PAGE_SIZE : process.env.EXPO_PUBLIC_DEFAULT_PAGE_SIZE,
  COVER_SERVER_URL : process.env.EXPO_PUBLIC_COVER_SERVER_URL,
};
